###################################################################################
###   Install Knative
###################################################################################
- name: Install Knative serving
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-crds.yaml
    - kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-core.yaml
    - kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-v1.8.1/kourier.yaml
    - kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}'
    - kubectl --namespace kourier-system get service kourier
    - kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-default-domain.yaml
    - kubectl patch configmap/config-domain -n knative-serving --type merge -p '{"data":{"10.195.9.114.sslip.io":""}}'
