pod_subnet: "${pod_subnet}"
cluster_name: "${cluster_name}"
docker_registry_url: "${docker_registry_url}"
docker_registry_username: "${docker_registry_username}"
docker_registry_password: "${docker_registry_password}"
docker_registry_email: "${docker_registry_email}"