
- name: Copy join command from Ansiblehost to the worker nodes.
  become: yes
  copy:
    src: ./kubernetes_join_command
    dest: /home/ubuntu/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes to the cluster.
  become: yes
  command: sh /home/ubuntu/kubernetes_join_command
  register: joined_or_not
